### ISSUE TITLE
BSL: bbinexpl with empty lists

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#21]
Should we handle empty lists, and how? It should be really easy to use "neutral values" for each operation:
- and: true
- or: false
- plus: 0
- mult: 1
- and so on

Do we want that? @andreaslindner @pablobuiras

**Comment by andreaslindner** [comment]
yes, it does make a lot of sense to me. in the end of the day it is a defined behavior.

**Comment by totorigolo** [comment]
Closing this as a wontfix, because we cannot return `0` (addition) or `1` (multiplication) because we would need to know the type of the expression. Let's keep BSL simple :)
