### ISSUE TITLE
Typo in lifter theorem?

### ISSUE THREAD

**Issue by andreaslindner** [kth-step/HolBA#44]
Should this be `bs'` instead?

https://github.com/kth-step/HolBA/blob/b49db276f12896eb3bb2f0049bdb2a969f2bf2de/src/theory/tools/lifter/bir_inst_liftingScript.sml#L2008

**Comment by didriklundberg** [comment]
Yes, this looks like a typo for sure. At the very least it is nonsensical since the conclusion resulting from the Running case is already an assumption in the theorem.
