### ISSUE TITLE
Duplicate theorems in bir_program_blocksTheory

### ISSUE THREAD

**Issue by didriklundberg** [kth-step/HolBA#53]
I was casually strolling through `bir_program_blocksScript.sml` when I noticed `bir_get_current_block_block_pc_IS_SOME` and `bir_get_current_block_block_pc`. These appear to be exactly identical. Therefore, I suggest we get rid of one of them. `bir_get_current_block_block_pc_IS_SOME` is used 1 times throughout the entirety of HolBA and `bir_get_current_block_block_pc` is used a grand total of zero times. I recommend `bir_get_current_block_block_pc` for removal, but first I want to give any eventual friends of `bir_get_current_block_block_pc` a possibility to have a say in the matter.

**Comment by totorigolo** [comment]
I will only say that we should keep the one with the more meaningful name, which I think is `bir_get_current_block_block_pc_IS_SOME`. Did you do `git blame` to see why and when it was added?

**Comment by didriklundberg** [comment]
> I will only say that we should keep the one with the more meaningful name, which I think is `bir_get_current_block_block_pc_IS_SOME`. Did you do `git blame` to see why and when it was added?

I did, but didn't gain any useful information from it. It seems to be just an accidentally duplicated lemma.

**Comment by andreaslindner** [comment]
It seems there are no friends of the shorter named one :)

**Comment by totorigolo** [comment]
<p align="center"><img src="https://media.giphy.com/media/3o6Mb4iDo3ne2U3M0o/giphy.gif" alt="Good bye :)"></p>
