### ISSUE TITLE
Installation instructions - PATH

### ISSUE THREAD

**Issue by totorigolo** [kth-step/HolBA#61]
Maybe we should mention how to add HOL4 to the PATH, or link to the HOL4 relevant documentation?

@andreaslindner what do you think?

**Comment by andreaslindner** [comment]
Yes, I think that is a good idea. We should do the same for emacs and mention the emacs config file.

**Comment by andreaslindner** [comment]
Actually, we could append the hol bin directory to the PATH in autoenv.sh and install_mk_env.sh. Do you think this would be a good place?

**Comment by totorigolo** [comment]
I think that it would make sense to assume that running `autoenv.sh` or the generated env file enables using `hol` or `Holmake`.
