### ISSUE TITLE
Generalized install scripts and instantiations

### ISSUE THREAD

**Issue by andreaslindner** [kth-step/HolBA#67]
Also add .installing files to indicate uncomplete runs

**Comment by totorigolo** [comment]
I already have played a little bit with this last month, so we can have a look at how I did it :)

**Comment by totorigolo** [comment]
Btw, can you explain more what you are thinking about in the title?

**Comment by andreaslindner** [comment]
We can talk about this in person and it's good if you have something already. The idea here is to generalize the existing install scripts into 2 or 3 kinds which are parametrizable and easy to instantiate (/call) for our existing dependencies (poly/hol/gcc/z3/embexp). In those we should add the .ok or .incomplete files and possibly the symbolic links you had in mind for holba_opt.

**Comment by totorigolo** [comment]
Closing for now because, while not perfect, the scripts just work. More work can be put here when/if needed later, for other dependencies or updates.
